sudo: required

language: ruby

services:
  - docker 

before_install:
  - docker build -t yeplaa/armhf-nginx:0.2 .
  - docker run -d -p 127.0.0.1:80:4567 yeplaa/armhf-nginx:0.2 /bin/sh -c "cd /root/armhf-nginx; bundle exec foreman start;"
  - docker ps -a
  - docker run yeplaa/armhf-nginx:0.2 /bin/sh -c "cd /root/armhf-nginx; bundle exec rake test"

script:
  - bundle exec rake test